main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('rescues/', views.rescues_index, name = 'index'),
    path('rescues/<int:rescue_id>/', views.rescues_detail, name = 'detail'),
    path('rescues/create', views.RescueCreate.as_view(), name = 'rescue_create'),
    path('rescues/<int:pk>/update/', views.RescueUpdate.as_view(), name = 'rescue_update'),
    path('rescues/<int:pk>/delete/', views.RescueDelete.as_view(), name = 'rescue_delete'),
    path('rescues/<int:rescue_id>/add_gift/', views.add_gift, name = 'add_gift'),
    path('rescues/<int:rescue_id>/assoc_adopter/<int:adopter_id>/', views.assoc_adopter, name = 'assoc_adopter'),
    path('rescues/<int:rescue_id>/disassoc_adopter/<int:adopter_id>/', views.disassoc_adopter, name = 'disassoc_adopter'),
    path('adopters/', views.AdopterList.as_view(), name = 'adopters_index'),
    path('adopters/<int:pk>/', views.AdopterDetail.as_view(), name = 'adopters_detail'),
    path('adopters/create/', views.AdopterCreate.as_view(), name = 'adopters_create'),
    path('adopters/<int:pk>/update/', views.AdopterUpdate.as_view(), name = 'adopters_update'),
    path('adopters/<int:pk>/delete/', views.AdopterDelete.as_view(), name = 'adopters_delete'),
    path('adopters/<int:rescue_id>/add_photo/', views.add_photo, name = 'add_photo'),
    ]

rescuecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
]

main_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Adopter(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)

    def __str__(self):
        return f'{self.name} has an id of {self.id}'
    
    def get_absolute_url(self):
        return reverse('adopters_detail', kwargs={'pk': self.id})


class Rescue(models.Model):
    name = models.CharField(max_length=100)
    animal = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    adopters = models.ManyToManyField(Adopter)

    def __str__(self):
        return f'{self.name} is a {self.animal} with an id of {self.id}'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'rescue_id': self.id})


class Gift(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateField()
    rescue = models.ForeignKey(Rescue, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} was provided on {self.date} to {self.rescue.name}'

    class Meta:
        ordering=['-date']

class Photo(models.Model):
    url = models.CharField(max_length=100)
    rescue = models.ForeignKey(Rescue, on_delete=models.CASCADE)

    def __str__(self):
        return f'the url is {self.url}'

main_app/forms.py
from django.forms import ModelForm
from .models import Gift

class GiftForm(ModelForm):
    class Meta:
        model = Gift
        fields = ['date', 'name']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Rescue, Adopter, Photo
from .forms import GiftForm
import uuid
import boto3

# Create your views here.


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def rescues_index(request):
    rescues = Rescue.objects.all()
    return render(request, 'rescues/index.html', {'rescues': rescues})

def rescues_detail(request, rescue_id):
    rescue = Rescue.objects.get(id=rescue_id)
    adopters_rescue_doesnt_have = Adopter.objects.exclude(id__in = rescue.adopters.all().values_list('id'))
    gift_form = GiftForm()
    return render(request, 'rescues/detail.html', {'rescue': rescue, 'gift_form': gift_form, 'adopters': adopters_rescue_doesnt_have})

class RescueCreate(CreateView):
    model = Rescue
    fields = '__all__'

class RescueUpdate(UpdateView):
    model = Rescue
    fields = ['animal', 'description', 'age']

class RescueDelete(DeleteView):
    model = Rescue
    success_url = '/rescues/'


def add_gift(request, rescue_id):
  form = GiftForm(request.POST)
  if form.is_valid():
    new_gift = form.save(commit=False)
    new_gift.rescue_id = rescue_id
    new_gift.save()
  return redirect('detail', rescue_id=rescue_id)

def assoc_adopter(request, rescue_id, adopter_id):
    Rescue.objects.get(id=rescue_id).adopters.add(adopter_id)
    return redirect('detail', rescue_id=rescue_id)

def disassoc_adopter(request, rescue_id, adopter_id):
    Rescue.objects.get(id=rescue_id).adopters.remove(adopter_id)
    return redirect('detail', rescue_id=rescue_id)

class AdopterList(ListView):
    model = Adopter

class AdopterDetail(DetailView):
    model = Adopter

class AdopterUpdate(UpdateView):
    model = Adopter
    fields = ['description']

class AdopterDelete(DeleteView):
    model = Adopter
    success_url = '/adopters/'

class AdopterCreate(CreateView):
    model = Adopter
    fields = '__all__'


def add_photo(request, rescue_id):
    S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
    BUCKET = 'catcollectorshawkitajima'
    rescue_photo = request.FILES.get('photo-file', None)
    if rescue_photo:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:7] + rescue_photo.name[rescue_photo.name.rfind('.'):]
        try:
            s3.upload_fileobj(rescue_photo, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, rescue_id = rescue_id)
            photo.save()
        except:
            print ('lol you done messed up')
    return redirect('detail', rescue_id=rescue_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>The Rescue Resource</h1>
<hr />
<p>We offer our rescues to be viewable online and allow users to request we provide our rescues with Gifts</p>
<p>Users may also apply to rescue our rescues</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Rescues!</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Rescue Recource</a></li>
        </ul>
        <ul class="right">
          <li><a href="/about">About</a></li>
          <li><a href="{% url 'adopters_create' %}">Create Adopter</a></li>
          <li><a href="{% url 'adopters_index' %}">View All Adopters</a></li>
          <li><a href="{% url 'rescue_create' %}">Create Rescue</a></li>
          <li><a href="/rescues">View All Rescues</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Rescue Resource &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/adopter_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Prospective Adopter</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'adopters_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/adopter_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Adopter Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ adopter.name }}</span>
        <p>Description: {{ adopter.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'adopters_update' adopter.id %}">Edit</a>
        <a href="{% url 'adopters_delete' adopter.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/adopter_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Adopter</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/adopter_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Adopter List</h1>

{% for adopter in adopter_list %}
  <a href="{% url 'adopters_detail' adopter.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ adopter.name }}</span>
            <p>Description: {{ adopter.description }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/rescue_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Rescue</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/rescue_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
        <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
        <h1>Add Rescue</h1>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>

{% endblock %}

main_app/templates/rescues/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Rescue Details</h1>
<div class="row">
    <div class="col s6">
      <div class="card">
        <div class="card-content">
          <span class="card-title">{{ rescue.name }}</span>
          <p>Type: {{ rescue.animal }}</p>
          <p>Description: {{ rescue.description }}</p>
          {% if rescue.age > 0 %}
            <p>Age: {{ rescue.age }}</p>
          {% else %}
            <p>Age: Baby</p>
          {% endif %}
        </div>
        <div class="card-action">
            <a href="{% url 'rescue_update' rescue.id %}">Edit</a>
            <a href="{% url 'rescue_delete' rescue.id %}">Delete</a>
        </div>
      </div>
      {% for photo in rescue.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' rescue.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <br><br>
        <input type="submit" class="btn" value="Upload Photo">
    </form>
    </div>
  <div class="col s6">
      <form action="{% url 'add_gift' rescue.id %}" method="post">
          {% csrf_token %}
          {{ gift_form.as_p }}
          <input type="submit" class="btn" value="Add Gift">
      </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Gift</th></tr>
      </thead>
      <tbody>
        {% for gift in rescue.gift_set.all %}
          <tr>
            <td>{{gift.date}}</td>
            <td>{{gift.name}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ rescue.name }}'s Prospective Adopters</h3>
    {% if rescue.adopters.count %}
      {% for adopter in rescue.adopters.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span>{{ adopter.name }}: </span> {{ adopter.description }}
            </span>
          </div>
          <div class="card-action">
              <form action="{% url 'disassoc_adopter' rescue.id adopter.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Remove</button>
              </form>
            </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No prospective adopters at this time :(</h5>
    {% endif %}
  </div>
  <!-- Available adopters will come after this line -->
  <div class="col s6">
      <h3>Available adopters</h3>
      {% if adopters.count %}
        {% for adopter in adopters.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                  <span>{{ adopter.name }}: </span> {{ adopter.description }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_adopter' rescue.id adopter.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{rescue.name}} Already Has All Prospective Adopters Available</h5>
      {% endif %}
    </div>
</div>

<script>
  let giftEl = document.getElementById('id_date')
  M.Datepicker.init(giftEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
</script>
{% endblock %}

main_app/templates/rescues/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Rescue List</h1>

{% for rescue in rescues %}
  <div class="card">
      <a href="{% url 'detail' rescue.id %}">
        <div class="card-content">
        <span class="card-title">{{ rescue.name }}</span>
        <p>Type: {{ rescue.animal }}</p>
        <p>Description: {{ rescue.description }}</p>
        {% if rescue.age > 0 %}
            <p>Age: {{ rescue.age }}</p>
        {% else %}
            <p>Age: Baby</p>
        {% endif %}
        </div>
    </a>
  </div>
{% endfor %}

{% endblock %}